// Code generated by gen-napi. DO NOT EDIT.
const { Tensor } = require('./tensor.cjs')
const {
  _toFloat32Array,
  _toFloat64Array,
  _toBoolInt8Array,
  _toInt16Array,
  _toInt32Array,
  _save,
  _toInt64Array,
  _toUint8Array,
  _toUint16Array,
  _toUint32Array,
  _toUint64Array,
  _toFloat32Scalar,
  _toFloat64Scalar,
  _toBoolInt8Scalar,
  _toInt16Scalar,
  _toInt32Scalar,
  _toInt64Scalar,
  _toUint8Scalar,
  _toUint16Scalar,
  _toUint32Scalar,
  _toUint64Scalar,
  _eval: __eval,
  _dispose,
  _tensorFromFloat32Buffer,
  _tensorFromFloat64Buffer,
  _tensorFromBoolInt8Buffer,
  _tensorFromInt16Buffer,
  _tensorFromInt32Buffer,
  _tensorFromInt64Buffer,
  _tensorFromUint8Buffer,
  _tensorFromUint16Buffer,
  _tensorFromUint32Buffer,
  _tensorFromUint64Buffer,
  _reshape,
  _absolute,
  _power,
  _argmin,
  _countNonzero,
  _full,
  _rint,
  _sort,
  _identity,
  _logicalNot,
  _isinf,
  _tril,
  _argmax,
  _ceil,
  _clip,
  _where,
  _maximum,
  _amax,
  _std,
  _cumsum,
  _transpose,
  _exp,
  _log,
  _sin,
  _sigmoid,
  _matmul,
  _amin,
  _var: __var,
  _norm,
  _all,
  _mean,
  _concatenate,
  _floor,
  _erf,
  _flip,
  _roll,
  _sign,
  _triu,
  _median,
  _tile,
  _log1p,
  _tanh,
  _isnan,
  _minimum,
  _any,
  _arange,
  _iota,
  _nonzero,
  _negative,
  _cos,
  _sqrt,
  _sum,
  _lessThan,
  _lessThanEqual,
  _logicalAnd,
  _mod,
  _bitwiseOr,
  _div,
  _neq,
  _mul,
  _rShift,
  _lShift,
  _greaterThanEqual,
  _logicalOr,
  _add,
  _bitwiseXor,
  _eq,
  _sub,
  _bitwiseAnd,
  _greaterThan,
  _init,
  _bytesUsed,
  _setRowMajor,
  _setColMajor,
  _isRowMajor,
  _isColMajor,
  _dtypeFloat32,
  _dtypeFloat64,
  _dtypeBoolInt8,
  _dtypeInt16,
  _dtypeInt32,
  _dtypeInt64,
  _dtypeUint8,
  _dtypeUint16,
  _dtypeUint32,
  _dtypeUint64,
  _rand,
  _randn
} = require('../../build/Release/shumai_bindings.node')

const isnan = (tensor) => {
  return new Tensor(_isnan(tensor._native_self))
}

const minimum = (lhs, rhs) => {
  return new Tensor(_minimum(lhs._native_self, rhs._native_self))
}

const any = (input, axes, keepDims) => {
  return new Tensor(_any(input._native_self, axes, keepDims))
}

const tile = (tensor, shape) => {
  return new Tensor(_tile(tensor._native_self, shape))
}

const log1p = (tensor) => {
  return new Tensor(_log1p(tensor._native_self))
}

const tanh = (tensor) => {
  return new Tensor(_tanh(tensor._native_self))
}

const negative = (tensor) => {
  return new Tensor(_negative(tensor._native_self))
}

const cos = (tensor) => {
  return new Tensor(_cos(tensor._native_self))
}

const sqrt = (tensor) => {
  return new Tensor(_sqrt(tensor._native_self))
}

const sum = (input, axes, keepDims) => {
  return new Tensor(_sum(input._native_self, axes, keepDims))
}

const arange = (start, end, step) => {
  return new Tensor(_arange(start, end, step))
}

const iota = (dims, tileDims) => {
  return new Tensor(_iota(dims, tileDims))
}

const nonzero = (tensor) => {
  return new Tensor(_nonzero(tensor._native_self))
}

const argmin = (input, axis, keepDims) => {
  return new Tensor(_argmin(input._native_self, axis, keepDims))
}

const countNonzero = (input, axes, keepDims) => {
  return new Tensor(_countNonzero(input._native_self, axes, keepDims))
}

const reshape = (tensor, shape) => {
  return new Tensor(_reshape(tensor._native_self, shape))
}

const absolute = (tensor) => {
  return new Tensor(_absolute(tensor._native_self))
}

const power = (lhs, rhs) => {
  return new Tensor(_power(lhs._native_self, rhs._native_self))
}

const full = (dims, val) => {
  return new Tensor(_full(dims, val))
}

const rint = (tensor) => {
  return new Tensor(_rint(tensor._native_self))
}

const sort = (input, axis) => {
  return new Tensor(_sort(input._native_self, axis))
}

const tril = (tensor) => {
  return new Tensor(_tril(tensor._native_self))
}

const argmax = (input, axis, keepDims) => {
  return new Tensor(_argmax(input._native_self, axis, keepDims))
}

const identity = (dim) => {
  return new Tensor(_identity(dim))
}

const logicalNot = (tensor) => {
  return new Tensor(_logicalNot(tensor._native_self))
}

const isinf = (tensor) => {
  return new Tensor(_isinf(tensor._native_self))
}

const maximum = (lhs, rhs) => {
  return new Tensor(_maximum(lhs._native_self, rhs._native_self))
}

const amax = (input, axes, keepDims) => {
  return new Tensor(_amax(input._native_self, axes, keepDims))
}

const std = (input, axes, keepDims) => {
  return new Tensor(_std(input._native_self, axes, keepDims))
}

const ceil = (tensor) => {
  return new Tensor(_ceil(tensor._native_self))
}

const clip = (tensor, low, high) => {
  return new Tensor(_clip(tensor._native_self, low._native_self, high._native_self))
}

const where = (condition, x, y) => {
  return new Tensor(_where(condition._native_self, x._native_self, y._native_self))
}

const sin = (tensor) => {
  return new Tensor(_sin(tensor._native_self))
}

const sigmoid = (tensor) => {
  return new Tensor(_sigmoid(tensor._native_self))
}

const matmul = (lhs, rhs) => {
  return new Tensor(_matmul(lhs._native_self, rhs._native_self))
}

const amin = (input, axes, keepDims) => {
  return new Tensor(_amin(input._native_self, axes, keepDims))
}

const cumsum = (input, axis) => {
  return new Tensor(_cumsum(input._native_self, axis))
}

const transpose = (tensor, axes) => {
  return new Tensor(_transpose(tensor._native_self, axes))
}

const exp = (tensor) => {
  return new Tensor(_exp(tensor._native_self))
}

const log = (tensor) => {
  return new Tensor(_log(tensor._native_self))
}

const _var = (input, axes, bias, keepDims) => {
  return new Tensor(__var(input._native_self, axes, bias, keepDims))
}

const norm = (input, axes, p, keepDims) => {
  return new Tensor(_norm(input._native_self, axes, p, keepDims))
}

const all = (input, axes, keepDims) => {
  return new Tensor(_all(input._native_self, axes, keepDims))
}

const flip = (tensor, dim) => {
  return new Tensor(_flip(tensor._native_self, dim))
}

const roll = (tensor, shift, axis) => {
  return new Tensor(_roll(tensor._native_self, shift, axis))
}

const sign = (tensor) => {
  return new Tensor(_sign(tensor._native_self))
}

const triu = (tensor) => {
  return new Tensor(_triu(tensor._native_self))
}

const mean = (input, axes, keepDims) => {
  return new Tensor(_mean(input._native_self, axes, keepDims))
}

const concatenate = (tensors, axis) => {
  return new Tensor(_concatenate(tensors, axis))
}

const floor = (tensor) => {
  return new Tensor(_floor(tensor._native_self))
}

const erf = (tensor) => {
  return new Tensor(_erf(tensor._native_self))
}

const median = (input, axes, keepDims) => {
  return new Tensor(_median(input._native_self, axes, keepDims))
}

const toFloat32Array = (tensor) => {
  return _toFloat32Array(tensor._native_self)
}

const toFloat64Array = (tensor) => {
  return _toFloat64Array(tensor._native_self)
}

const toBoolInt8Array = (tensor) => {
  return _toBoolInt8Array(tensor._native_self)
}

const toInt16Array = (tensor) => {
  return _toInt16Array(tensor._native_self)
}

const toInt32Array = (tensor) => {
  return _toInt32Array(tensor._native_self)
}

const save = (filename) => {
  return _save(filename)
}

const toInt64Array = (tensor) => {
  return _toInt64Array(tensor._native_self)
}

const toUint8Array = (tensor) => {
  return _toUint8Array(tensor._native_self)
}

const toUint16Array = (tensor) => {
  return _toUint16Array(tensor._native_self)
}

const toUint32Array = (tensor) => {
  return _toUint32Array(tensor._native_self)
}

const toUint64Array = (tensor) => {
  return _toUint64Array(tensor._native_self)
}

const toFloat32Scalar = (tensor) => {
  return _toFloat32Scalar(tensor._native_self)
}

const toFloat64Scalar = (tensor) => {
  return _toFloat64Scalar(tensor._native_self)
}

const toBoolInt8Scalar = (tensor) => {
  return _toBoolInt8Scalar(tensor._native_self)
}

const toInt16Scalar = (tensor) => {
  return _toInt16Scalar(tensor._native_self)
}

const toInt32Scalar = (tensor) => {
  return _toInt32Scalar(tensor._native_self)
}

const toInt64Scalar = (tensor) => {
  return _toInt64Scalar(tensor._native_self)
}

const toUint8Scalar = (tensor) => {
  return _toUint8Scalar(tensor._native_self)
}

const toUint16Scalar = (tensor) => {
  return _toUint16Scalar(tensor._native_self)
}

const toUint32Scalar = (tensor) => {
  return _toUint32Scalar(tensor._native_self)
}

const toUint64Scalar = (tensor) => {
  return _toUint64Scalar(tensor._native_self)
}

const _eval = (tensor) => {
  return __eval(tensor._native_self)
}

const dispose = (tensor) => {
  return _dispose(tensor._native_self)
}

const tensorFromFloat32Buffer = (arr) => {
  return _tensorFromFloat32Buffer(arr.buffer)
}

const tensorFromFloat64Buffer = (arr) => {
  return _tensorFromFloat64Buffer(arr.buffer)
}

const tensorFromBoolInt8Buffer = (arr) => {
  return _tensorFromBoolInt8Buffer(arr.buffer)
}

const tensorFromInt16Buffer = (arr) => {
  return _tensorFromInt16Buffer(arr.buffer)
}

const tensorFromInt32Buffer = (arr) => {
  return _tensorFromInt32Buffer(arr.buffer)
}

const tensorFromInt64Buffer = (arr) => {
  return _tensorFromInt64Buffer(arr.buffer)
}

const tensorFromUint8Buffer = (arr) => {
  return _tensorFromUint8Buffer(arr.buffer)
}

const tensorFromUint16Buffer = (arr) => {
  return _tensorFromUint16Buffer(arr.buffer)
}

const tensorFromUint32Buffer = (arr) => {
  return _tensorFromUint32Buffer(arr.buffer)
}

const tensorFromUint64Buffer = (arr) => {
  return _tensorFromUint64Buffer(arr.buffer)
}

const bitwiseXor = (lhs, rhs) => {
  return new Tensor(_bitwiseXor(lhs._native_self, rhs._native_self))
}

const greaterThanEqual = (lhs, rhs) => {
  return new Tensor(_greaterThanEqual(lhs._native_self, rhs._native_self))
}

const logicalOr = (lhs, rhs) => {
  return new Tensor(_logicalOr(lhs._native_self, rhs._native_self))
}

const add = (lhs, rhs) => {
  return new Tensor(_add(lhs._native_self, rhs._native_self))
}

const greaterThan = (lhs, rhs) => {
  return new Tensor(_greaterThan(lhs._native_self, rhs._native_self))
}

const eq = (lhs, rhs) => {
  return new Tensor(_eq(lhs._native_self, rhs._native_self))
}

const sub = (lhs, rhs) => {
  return new Tensor(_sub(lhs._native_self, rhs._native_self))
}

const bitwiseAnd = (lhs, rhs) => {
  return new Tensor(_bitwiseAnd(lhs._native_self, rhs._native_self))
}

const bitwiseOr = (lhs, rhs) => {
  return new Tensor(_bitwiseOr(lhs._native_self, rhs._native_self))
}

const lessThan = (lhs, rhs) => {
  return new Tensor(_lessThan(lhs._native_self, rhs._native_self))
}

const lessThanEqual = (lhs, rhs) => {
  return new Tensor(_lessThanEqual(lhs._native_self, rhs._native_self))
}

const logicalAnd = (lhs, rhs) => {
  return new Tensor(_logicalAnd(lhs._native_self, rhs._native_self))
}

const mod = (lhs, rhs) => {
  return new Tensor(_mod(lhs._native_self, rhs._native_self))
}

const lShift = (lhs, rhs) => {
  return new Tensor(_lShift(lhs._native_self, rhs._native_self))
}

const div = (lhs, rhs) => {
  return new Tensor(_div(lhs._native_self, rhs._native_self))
}

const neq = (lhs, rhs) => {
  return new Tensor(_neq(lhs._native_self, rhs._native_self))
}

const mul = (lhs, rhs) => {
  return new Tensor(_mul(lhs._native_self, rhs._native_self))
}

const rShift = (lhs, rhs) => {
  return new Tensor(_rShift(lhs._native_self, rhs._native_self))
}

const init = () => {
  return _init()
}

const bytesUsed = () => {
  return _bytesUsed()
}

const setRowMajor = () => {
  return _setRowMajor()
}

const setColMajor = () => {
  return _setColMajor()
}

const isRowMajor = () => {
  return _isRowMajor()
}

const isColMajor = () => {
  return _isColMajor()
}

const dtypeFloat32 = () => {
  return _dtypeFloat32()
}

const dtypeFloat64 = () => {
  return _dtypeFloat64()
}

const dtypeBoolInt8 = () => {
  return _dtypeBoolInt8()
}

const dtypeInt16 = () => {
  return _dtypeInt16()
}

const dtypeInt32 = () => {
  return _dtypeInt32()
}

const dtypeInt64 = () => {
  return _dtypeInt64()
}

const dtypeUint8 = () => {
  return _dtypeUint8()
}

const dtypeUint16 = () => {
  return _dtypeUint16()
}

const dtypeUint32 = () => {
  return _dtypeUint32()
}

const dtypeUint64 = () => {
  return _dtypeUint64()
}

const rand = (shape) => {
  return new Tensor(_rand(shape))
}

const randn = (shape) => {
  return new Tensor(_randn(shape))
}

module.exports = {
  minimum,
  any,
  tile,
  log1p,
  tanh,
  isnan,
  cos,
  sqrt,
  sum,
  arange,
  iota,
  nonzero,
  negative,
  countNonzero,
  reshape,
  absolute,
  power,
  argmin,
  full,
  rint,
  sort,
  argmax,
  identity,
  logicalNot,
  isinf,
  tril,
  amax,
  std,
  ceil,
  clip,
  where,
  maximum,
  sigmoid,
  matmul,
  amin,
  cumsum,
  transpose,
  exp,
  log,
  sin,
  _var,
  norm,
  all,
  roll,
  sign,
  triu,
  mean,
  concatenate,
  floor,
  erf,
  flip,
  median,
  neq,
  mul,
  rShift,
  lShift,
  div,
  logicalOr,
  add,
  bitwiseXor,
  greaterThanEqual,
  sub,
  bitwiseAnd,
  greaterThan,
  eq,
  lessThanEqual,
  logicalAnd,
  mod,
  bitwiseOr,
  lessThan,
  init,
  bytesUsed,
  setRowMajor,
  setColMajor,
  isRowMajor,
  isColMajor,
  dtypeFloat32,
  dtypeFloat64,
  dtypeBoolInt8,
  dtypeInt16,
  dtypeInt32,
  dtypeInt64,
  dtypeUint8,
  dtypeUint16,
  dtypeUint32,
  dtypeUint64,
  rand,
  randn,
  toFloat32Array,
  toFloat64Array,
  toBoolInt8Array,
  toInt16Array,
  toInt32Array,
  save,
  toInt64Array,
  toUint8Array,
  toUint16Array,
  toUint32Array,
  toUint64Array,
  toFloat32Scalar,
  toFloat64Scalar,
  toBoolInt8Scalar,
  toInt16Scalar,
  toInt32Scalar,
  toInt64Scalar,
  toUint8Scalar,
  toUint16Scalar,
  toUint32Scalar,
  toUint64Scalar,
  _eval,
  dispose,
  tensorFromFloat32Buffer,
  tensorFromFloat64Buffer,
  tensorFromBoolInt8Buffer,
  tensorFromInt16Buffer,
  tensorFromInt32Buffer,
  tensorFromInt64Buffer,
  tensorFromUint8Buffer,
  tensorFromUint16Buffer,
  tensorFromUint32Buffer,
  tensorFromUint64Buffer
}
