// Code generated by gen-napi. DO NOT EDIT.
const {
	_Tensor,
	_iota,
	_tanh,
	_sigmoid,
	_power,
	_log1p,
	_sqrt,
	_tril,
	_where,
	_clip,
	_arange,
	_tile,
	_cos,
	_floor,
	_flip,
	_triu,
	_minimum,
	_argmax,
	_full,
	_reshape,
	_negative,
	_log,
	_countNonzero,
	_sum,
	_var: __var,
	_std,
	_norm,
	_identity,
	_exp,
	_ceil,
	_absolute,
	_sort,
	_amax,
	_median,
	_nonzero,
	_erf,
	_roll,
	_sign,
	_any,
	_sin,
	_matmul,
	_argmin,
	_mean,
	_isnan,
	_isinf,
	_maximum,
	_amin,
	_transpose,
	_concatenate,
	_logicalNot,
	_rint,
	_cumsum,
	_all,
	_rShift,
	_lessThan,
	_lShift,
	_lessThanEqual,
	_eq,
	_greaterThan,
	_bitwiseOr,
	_add,
	_neq,
	_logicalAnd,
	_sub,
	_div,
	_bitwiseAnd,
	_mul,
	_logicalOr,
	_mod,
	_bitwiseXor,
	_greaterThanEqual,
	_init,
	_bytesUsed,
	_setRowMajor,
	_setColMajor,
	_isRowMajor,
	_isColMajor,
	_dtypeFloat32,
	_dtypeFloat64,
	_dtypeBoolInt8,
	_dtypeInt16,
	_dtypeInt32,
	_dtypeInt64,
	_dtypeUint8,
	_dtypeUint16,
	_dtypeUint32,
	_dtypeUint64,
	_rand,
	_randn
} = require("../../build/Release/flashlight_napi_bindings.node")

export class Tensor {
	private #_native_self: any;

	constructor(t) {
		this.#_native_self = new _Tensor(t);
	}

	get _native_self() {
		return this.#_native_self;
	}

	tile(shape: Shape): Tensor {
		return this.#_native_self.tile(shape);
	}

	cos(): Tensor {
		return this.#_native_self.cos();
	}

	floor(): Tensor {
		return this.#_native_self.floor();
	}

	clip(low: Tensor, high: Tensor): Tensor {
		return this.#_native_self.clip(low.#_native_self, high.#_native_self);
	}

	reshape(shape: Shape): Tensor {
		return this.#_native_self.reshape(shape);
	}

	negative(): Tensor {
		return this.#_native_self.negative();
	}

	log(): Tensor {
		return this.#_native_self.log();
	}

	flip(dim: number): Tensor {
		return this.#_native_self.flip(dim);
	}

	triu(): Tensor {
		return this.#_native_self.triu();
	}

	countNonzero(axes: std::vector<int>, keepDims: boolean): Tensor {
		return this.#_native_self.countNonzero(axes, keepDims);
	}

	norm(axes: std::vector<int>, p: number, keepDims: boolean): Tensor {
		return this.#_native_self.norm(axes, p, keepDims);
	}

	exp(): Tensor {
		return this.#_native_self.exp();
	}

	ceil(): Tensor {
		return this.#_native_self.ceil();
	}

	absolute(): Tensor {
		return this.#_native_self.absolute();
	}

	sum(axes: std::vector<int>, keepDims: boolean): Tensor {
		return this.#_native_self.sum(axes, keepDims);
	}

	var(axes: std::vector<int>, bias: boolean, keepDims: boolean): Tensor {
		return this.#_native_self.var(axes, bias, keepDims);
	}

	std(axes: std::vector<int>, keepDims: boolean): Tensor {
		return this.#_native_self.std(axes, keepDims);
	}

	nonzero(): Tensor {
		return this.#_native_self.nonzero();
	}

	erf(): Tensor {
		return this.#_native_self.erf();
	}

	roll(shift: number, axis: number): Tensor {
		return this.#_native_self.roll(shift, axis);
	}

	sign(): Tensor {
		return this.#_native_self.sign();
	}

	sort(axis: Dim, sortMode: SortMode): Tensor {
		return this.#_native_self.sort(axis, sortMode);
	}

	amax(axes: std::vector<int>, keepDims: boolean): Tensor {
		return this.#_native_self.amax(axes, keepDims);
	}

	median(axes: std::vector<int>, keepDims: boolean): Tensor {
		return this.#_native_self.median(axes, keepDims);
	}

	sin(): Tensor {
		return this.#_native_self.sin();
	}

	matmul(rhs: Tensor, lhsProp: MatrixProperty, rhsProp: MatrixProperty): Tensor {
		return this.#_native_self.matmul(rhs.#_native_self, lhsProp, rhsProp);
	}

	argmin(axis: number, keepDims: boolean): Tensor {
		return this.#_native_self.argmin(axis, keepDims);
	}

	mean(axes: std::vector<int>, keepDims: boolean): Tensor {
		return this.#_native_self.mean(axes, keepDims);
	}

	any(axes: std::vector<int>, keepDims: boolean): Tensor {
		return this.#_native_self.any(axes, keepDims);
	}

	amin(axes: std::vector<int>, keepDims: boolean): Tensor {
		return this.#_native_self.amin(axes, keepDims);
	}

	transpose(axes: Shape): Tensor {
		return this.#_native_self.transpose(axes);
	}

	logicalNot(): Tensor {
		return this.#_native_self.logicalNot();
	}

	rint(): Tensor {
		return this.#_native_self.rint();
	}

	isnan(): Tensor {
		return this.#_native_self.isnan();
	}

	isinf(): Tensor {
		return this.#_native_self.isinf();
	}

	maximum(rhs: Tensor): Tensor {
		return this.#_native_self.maximum(rhs.#_native_self);
	}

	cumsum(axis: number): Tensor {
		return this.#_native_self.cumsum(axis);
	}

	all(axes: std::vector<int>, keepDims: boolean): Tensor {
		return this.#_native_self.all(axes, keepDims);
	}

	tanh(): Tensor {
		return this.#_native_self.tanh();
	}

	sigmoid(): Tensor {
		return this.#_native_self.sigmoid();
	}

	power(rhs: Tensor): Tensor {
		return this.#_native_self.power(rhs.#_native_self);
	}

	log1p(): Tensor {
		return this.#_native_self.log1p();
	}

	sqrt(): Tensor {
		return this.#_native_self.sqrt();
	}

	tril(): Tensor {
		return this.#_native_self.tril();
	}

	where(x: Tensor, y: Tensor): Tensor {
		return this.#_native_self.where(x.#_native_self, y.#_native_self);
	}

	sub(rhs: Tensor): Tensor {
		return this.#_native_self.sub(rhs.#_native_self);
	}

	div(rhs: Tensor): Tensor {
		return this.#_native_self.div(rhs.#_native_self);
	}

	bitwiseAnd(rhs: Tensor): Tensor {
		return this.#_native_self.bitwiseAnd(rhs.#_native_self);
	}

	mul(rhs: Tensor): Tensor {
		return this.#_native_self.mul(rhs.#_native_self);
	}

	logicalOr(rhs: Tensor): Tensor {
		return this.#_native_self.logicalOr(rhs.#_native_self);
	}

	mod(rhs: Tensor): Tensor {
		return this.#_native_self.mod(rhs.#_native_self);
	}

	bitwiseXor(rhs: Tensor): Tensor {
		return this.#_native_self.bitwiseXor(rhs.#_native_self);
	}

	greaterThanEqual(rhs: Tensor): Tensor {
		return this.#_native_self.greaterThanEqual(rhs.#_native_self);
	}

	rShift(rhs: Tensor): Tensor {
		return this.#_native_self.rShift(rhs.#_native_self);
	}

	lessThan(rhs: Tensor): Tensor {
		return this.#_native_self.lessThan(rhs.#_native_self);
	}

	lShift(rhs: Tensor): Tensor {
		return this.#_native_self.lShift(rhs.#_native_self);
	}

	lessThanEqual(rhs: Tensor): Tensor {
		return this.#_native_self.lessThanEqual(rhs.#_native_self);
	}

	bitwiseOr(rhs: Tensor): Tensor {
		return this.#_native_self.bitwiseOr(rhs.#_native_self);
	}

	add(rhs: Tensor): Tensor {
		return this.#_native_self.add(rhs.#_native_self);
	}

	neq(rhs: Tensor): Tensor {
		return this.#_native_self.neq(rhs.#_native_self);
	}

	logicalAnd(rhs: Tensor): Tensor {
		return this.#_native_self.logicalAnd(rhs.#_native_self);
	}

	eq(rhs: Tensor): Tensor {
		return this.#_native_self.eq(rhs.#_native_self);
	}

	greaterThan(rhs: Tensor): Tensor {
		return this.#_native_self.greaterThan(rhs.#_native_self);
	}

	copy(): void {
		return this.#_native_self.copy();
	}

	shape(): void {
		return this.#_native_self.shape();
	}

	elements(): void {
		return this.#_native_self.elements();
	}

	ndim(): void {
		return this.#_native_self.ndim();
	}

	isEmpty(): void {
		return this.#_native_self.isEmpty();
	}

	bytes(): void {
		return this.#_native_self.bytes();
	}

	type(): void {
		return this.#_native_self.type();
	}

	isSparse(): void {
		return this.#_native_self.isSparse();
	}

	strides(): void {
		return this.#_native_self.strides();
	}

	astype(): void {
		return this.#_native_self.astype();
	}

	flatten(): void {
		return this.#_native_self.flatten();
	}

	asContiguousTensor(): void {
		return this.#_native_self.asContiguousTensor();
	}

	isContiguous(): void {
		return this.#_native_self.isContiguous();
	}

	toFloat32Array(): any {
		return this.#_native_self.toFloat32Array();
	}

	toFloat64Array(): any {
		return this.#_native_self.toFloat64Array();
	}

	toBoolInt8Array(): any {
		return this.#_native_self.toBoolInt8Array();
	}

	toInt16Array(): any {
		return this.#_native_self.toInt16Array();
	}

	toInt32Array(): any {
		return this.#_native_self.toInt32Array();
	}

	toInt64Array(): any {
		return this.#_native_self.toInt64Array();
	}

	toUint8Array(): any {
		return this.#_native_self.toUint8Array();
	}

	toUint16Array(): any {
		return this.#_native_self.toUint16Array();
	}

	toUint32Array(): any {
		return this.#_native_self.toUint32Array();
	}

	toUint64Array(): any {
		return this.#_native_self.toUint64Array();
	}

	toFloat32Scalar(): any {
		return this.#_native_self.toFloat32Scalar();
	}

	toFloat64Scalar(): any {
		return this.#_native_self.toFloat64Scalar();
	}

	toBoolInt8Scalar(): any {
		return this.#_native_self.toBoolInt8Scalar();
	}

	toInt16Scalar(): any {
		return this.#_native_self.toInt16Scalar();
	}

	toInt32Scalar(): any {
		return this.#_native_self.toInt32Scalar();
	}

	toInt64Scalar(): any {
		return this.#_native_self.toInt64Scalar();
	}

	toUint8Scalar(): any {
		return this.#_native_self.toUint8Scalar();
	}

	toUint16Scalar(): any {
		return this.#_native_self.toUint16Scalar();
	}

	toUint32Scalar(): any {
		return this.#_native_self.toUint32Scalar();
	}

	toUint64Scalar(): any {
		return this.#_native_self.toUint64Scalar();
	}

	eval(): any {
		return this.#_native_self.eval();
	}

	dispose(): any {
		return this.#_native_self.dispose();
	}

}

const argmax = (input, axis, keepDims) => {
	return _argmax(input._native_self, axis, keepDims);
}

const full = (dims, val, type) => {
	return _full(dims, val, type);
}

const reshape = (tensor, shape) => {
	return _reshape(tensor._native_self, shape);
}

const negative = (tensor) => {
	return _negative(tensor._native_self);
}

const log = (tensor) => {
	return _log(tensor._native_self);
}

const flip = (tensor, dim) => {
	return _flip(tensor._native_self, dim);
}

const triu = (tensor) => {
	return _triu(tensor._native_self);
}

const minimum = (lhs, rhs) => {
	return _minimum(lhs._native_self, rhs._native_self);
}

const countNonzero = (input, axes, keepDims) => {
	return _countNonzero(input._native_self, axes, keepDims);
}

const norm = (input, axes, p, keepDims) => {
	return _norm(input._native_self, axes, p, keepDims);
}

const identity = (dim, type) => {
	return _identity(dim, type);
}

const exp = (tensor) => {
	return _exp(tensor._native_self);
}

const ceil = (tensor) => {
	return _ceil(tensor._native_self);
}

const absolute = (tensor) => {
	return _absolute(tensor._native_self);
}

const sum = (input, axes, keepDims) => {
	return _sum(input._native_self, axes, keepDims);
}

const _var = (input, axes, bias, keepDims) => {
	return __var(input._native_self, axes, bias, keepDims);
}

const std = (input, axes, keepDims) => {
	return _std(input._native_self, axes, keepDims);
}

const nonzero = (tensor) => {
	return _nonzero(tensor._native_self);
}

const erf = (tensor) => {
	return _erf(tensor._native_self);
}

const roll = (tensor, shift, axis) => {
	return _roll(tensor._native_self, shift, axis);
}

const sign = (tensor) => {
	return _sign(tensor._native_self);
}

const sort = (input, axis, sortMode) => {
	return _sort(input._native_self, axis, sortMode);
}

const amax = (input, axes, keepDims) => {
	return _amax(input._native_self, axes, keepDims);
}

const median = (input, axes, keepDims) => {
	return _median(input._native_self, axes, keepDims);
}

const sin = (tensor) => {
	return _sin(tensor._native_self);
}

const matmul = (lhs, rhs, lhsProp, rhsProp) => {
	return _matmul(lhs._native_self, rhs._native_self, lhsProp, rhsProp);
}

const argmin = (input, axis, keepDims) => {
	return _argmin(input._native_self, axis, keepDims);
}

const mean = (input, axes, keepDims) => {
	return _mean(input._native_self, axes, keepDims);
}

const any = (input, axes, keepDims) => {
	return _any(input._native_self, axes, keepDims);
}

const amin = (input, axes, keepDims) => {
	return _amin(input._native_self, axes, keepDims);
}

const transpose = (tensor, axes) => {
	return _transpose(tensor._native_self, axes);
}

const concatenate = (tensors, axis) => {
	return _concatenate(tensors, axis);
}

const logicalNot = (tensor) => {
	return _logicalNot(tensor._native_self);
}

const rint = (tensor) => {
	return _rint(tensor._native_self);
}

const isnan = (tensor) => {
	return _isnan(tensor._native_self);
}

const isinf = (tensor) => {
	return _isinf(tensor._native_self);
}

const maximum = (lhs, rhs) => {
	return _maximum(lhs._native_self, rhs._native_self);
}

const cumsum = (input, axis) => {
	return _cumsum(input._native_self, axis);
}

const all = (input, axes, keepDims) => {
	return _all(input._native_self, axes, keepDims);
}

const iota = (dims, tileDims, type) => {
	return _iota(dims, tileDims, type);
}

const tanh = (tensor) => {
	return _tanh(tensor._native_self);
}

const sigmoid = (tensor) => {
	return _sigmoid(tensor._native_self);
}

const power = (lhs, rhs) => {
	return _power(lhs._native_self, rhs._native_self);
}

const log1p = (tensor) => {
	return _log1p(tensor._native_self);
}

const sqrt = (tensor) => {
	return _sqrt(tensor._native_self);
}

const tril = (tensor) => {
	return _tril(tensor._native_self);
}

const where = (condition, x, y) => {
	return _where(condition._native_self, x._native_self, y._native_self);
}

const arange = (start, end, step, type) => {
	return _arange(start, end, step, type);
}

const tile = (tensor, shape) => {
	return _tile(tensor._native_self, shape);
}

const cos = (tensor) => {
	return _cos(tensor._native_self);
}

const floor = (tensor) => {
	return _floor(tensor._native_self);
}

const clip = (tensor, low, high) => {
	return _clip(tensor._native_self, low._native_self, high._native_self);
}

const logicalAnd = (lhs, rhs) => {
	return _logicalAnd(lhs._native_self, rhs._native_self);
}

const eq = (lhs, rhs) => {
	return _eq(lhs._native_self, rhs._native_self);
}

const greaterThan = (lhs, rhs) => {
	return _greaterThan(lhs._native_self, rhs._native_self);
}

const bitwiseOr = (lhs, rhs) => {
	return _bitwiseOr(lhs._native_self, rhs._native_self);
}

const add = (lhs, rhs) => {
	return _add(lhs._native_self, rhs._native_self);
}

const neq = (lhs, rhs) => {
	return _neq(lhs._native_self, rhs._native_self);
}

const mul = (lhs, rhs) => {
	return _mul(lhs._native_self, rhs._native_self);
}

const sub = (lhs, rhs) => {
	return _sub(lhs._native_self, rhs._native_self);
}

const div = (lhs, rhs) => {
	return _div(lhs._native_self, rhs._native_self);
}

const bitwiseAnd = (lhs, rhs) => {
	return _bitwiseAnd(lhs._native_self, rhs._native_self);
}

const greaterThanEqual = (lhs, rhs) => {
	return _greaterThanEqual(lhs._native_self, rhs._native_self);
}

const logicalOr = (lhs, rhs) => {
	return _logicalOr(lhs._native_self, rhs._native_self);
}

const mod = (lhs, rhs) => {
	return _mod(lhs._native_self, rhs._native_self);
}

const bitwiseXor = (lhs, rhs) => {
	return _bitwiseXor(lhs._native_self, rhs._native_self);
}

const lessThanEqual = (lhs, rhs) => {
	return _lessThanEqual(lhs._native_self, rhs._native_self);
}

const rShift = (lhs, rhs) => {
	return _rShift(lhs._native_self, rhs._native_self);
}

const lessThan = (lhs, rhs) => {
	return _lessThan(lhs._native_self, rhs._native_self);
}

const lShift = (lhs, rhs) => {
	return _lShift(lhs._native_self, rhs._native_self);
}

const init = () => {
	return _init();
}

const bytesUsed = () => {
	return _bytesUsed();
}

const setRowMajor = () => {
	return _setRowMajor();
}

const setColMajor = () => {
	return _setColMajor();
}

const isRowMajor = () => {
	return _isRowMajor();
}

const isColMajor = () => {
	return _isColMajor();
}

const dtypeFloat32 = () => {
	return _dtypeFloat32();
}

const dtypeFloat64 = () => {
	return _dtypeFloat64();
}

const dtypeBoolInt8 = () => {
	return _dtypeBoolInt8();
}

const dtypeInt16 = () => {
	return _dtypeInt16();
}

const dtypeInt32 = () => {
	return _dtypeInt32();
}

const dtypeInt64 = () => {
	return _dtypeInt64();
}

const dtypeUint8 = () => {
	return _dtypeUint8();
}

const dtypeUint16 = () => {
	return _dtypeUint16();
}

const dtypeUint32 = () => {
	return _dtypeUint32();
}

const dtypeUint64 = () => {
	return _dtypeUint64();
}

const rand = (shape) => {
	return _rand(shape);
}

const randn = (shape) => {
	return _randn(shape);
}

