// Code generated by gen-napi. DO NOT EDIT.
const {
  _Tensor,
  _transpose,
  _sigmoid,
  _roll,
  _isnan,
  _where,
  _sort,
  _full,
  _identity,
  _sum,
  _median,
  _argmin,
  _mean,
  _var: __var,
  _nonzero,
  _sqrt,
  _rint,
  _flip,
  _power,
  _norm,
  _countNonzero,
  _concatenate,
  _exp,
  _amax,
  _cumsum,
  _any,
  _cos,
  _minimum,
  _absolute,
  _isinf,
  _triu,
  _argmax,
  _tile,
  _logicalNot,
  _log1p,
  _sign,
  _tril,
  _maximum,
  _amin,
  _iota,
  _log,
  _negative,
  _tanh,
  _floor,
  _std,
  _all,
  _arange,
  _reshape,
  _erf,
  _clip,
  _matmul,
  _sin,
  _ceil,
  _greaterThanEqual,
  _bitwiseOr,
  _mul,
  _lessThanEqual,
  _mod,
  _lessThan,
  _bitwiseAnd,
  _eq,
  _bitwiseXor,
  _add,
  _sub,
  _logicalAnd,
  _lShift,
  _logicalOr,
  _neq,
  _rShift,
  _div,
  _greaterThan,
  _init,
  _bytesUsed,
  _setRowMajor,
  _setColMajor,
  _isRowMajor,
  _isColMajor,
  _dtypeFloat32,
  _dtypeFloat64,
  _dtypeBoolInt8,
  _dtypeInt16,
  _dtypeInt32,
  _dtypeInt64,
  _dtypeUint8,
  _dtypeUint16,
  _dtypeUint32,
  _dtypeUint64,
  _rand,
  _randn
} = require('../../build/Release/flashlight_napi_bindings.node')

class Tensor {
  #_native_self

  constructor(t) {
    this.#_native_self = new _Tensor(t)
  }

  get _native_self() {
    return this.#_native_self
  }

  norm(axes, p, keepDims) {
    return new Tensor(this.#_native_self.norm(axes, p, keepDims))
  }

  countNonzero(axes, keepDims) {
    return new Tensor(this.#_native_self.countNonzero(axes, keepDims))
  }

  exp() {
    return new Tensor(this.#_native_self.exp())
  }

  rint() {
    return new Tensor(this.#_native_self.rint())
  }

  flip(dim) {
    return new Tensor(this.#_native_self.flip(dim))
  }

  power(rhs) {
    return new Tensor(this.#_native_self.power(rhs.#_native_self))
  }

  cos() {
    return new Tensor(this.#_native_self.cos())
  }

  amax(axes, keepDims) {
    return new Tensor(this.#_native_self.amax(axes, keepDims))
  }

  cumsum(axis) {
    return new Tensor(this.#_native_self.cumsum(axis))
  }

  any(axes, keepDims) {
    return new Tensor(this.#_native_self.any(axes, keepDims))
  }

  tile(shape) {
    return new Tensor(this.#_native_self.tile(shape))
  }

  logicalNot() {
    return new Tensor(this.#_native_self.logicalNot())
  }

  absolute() {
    return new Tensor(this.#_native_self.absolute())
  }

  isinf() {
    return new Tensor(this.#_native_self.isinf())
  }

  triu() {
    return new Tensor(this.#_native_self.triu())
  }

  maximum(rhs) {
    return new Tensor(this.#_native_self.maximum(rhs.#_native_self))
  }

  amin(axes, keepDims) {
    return new Tensor(this.#_native_self.amin(axes, keepDims))
  }

  log() {
    return new Tensor(this.#_native_self.log())
  }

  log1p() {
    return new Tensor(this.#_native_self.log1p())
  }

  sign() {
    return new Tensor(this.#_native_self.sign())
  }

  tril() {
    return new Tensor(this.#_native_self.tril())
  }

  std(axes, keepDims) {
    return new Tensor(this.#_native_self.std(axes, keepDims))
  }

  all(axes, keepDims) {
    return new Tensor(this.#_native_self.all(axes, keepDims))
  }

  reshape(shape) {
    return new Tensor(this.#_native_self.reshape(shape))
  }

  negative() {
    return new Tensor(this.#_native_self.negative())
  }

  tanh() {
    return new Tensor(this.#_native_self.tanh())
  }

  floor() {
    return new Tensor(this.#_native_self.floor())
  }

  sin() {
    return new Tensor(this.#_native_self.sin())
  }

  ceil() {
    return new Tensor(this.#_native_self.ceil())
  }

  erf() {
    return new Tensor(this.#_native_self.erf())
  }

  clip(low, high) {
    return new Tensor(this.#_native_self.clip(low.#_native_self, high.#_native_self))
  }

  matmul(rhs) {
    return new Tensor(this.#_native_self.matmul(rhs.#_native_self))
  }

  isnan() {
    return new Tensor(this.#_native_self.isnan())
  }

  where(x, y) {
    return new Tensor(this.#_native_self.where(x.#_native_self, y.#_native_self))
  }

  sort(axis) {
    return new Tensor(this.#_native_self.sort(axis))
  }

  transpose(axes) {
    return new Tensor(this.#_native_self.transpose(axes))
  }

  sigmoid() {
    return new Tensor(this.#_native_self.sigmoid())
  }

  roll(shift, axis) {
    return new Tensor(this.#_native_self.roll(shift, axis))
  }

  sum(axes, keepDims) {
    return new Tensor(this.#_native_self.sum(axes, keepDims))
  }

  median(axes, keepDims) {
    return new Tensor(this.#_native_self.median(axes, keepDims))
  }

  nonzero() {
    return new Tensor(this.#_native_self.nonzero())
  }

  sqrt() {
    return new Tensor(this.#_native_self.sqrt())
  }

  argmin(axis, keepDims) {
    return new Tensor(this.#_native_self.argmin(axis, keepDims))
  }

  mean(axes, keepDims) {
    return new Tensor(this.#_native_self.mean(axes, keepDims))
  }

  var(axes, bias, keepDims) {
    return new Tensor(this.#_native_self.var(axes, bias, keepDims))
  }

  mod(rhs) {
    return new Tensor(this.#_native_self.mod(rhs.#_native_self))
  }

  lessThan(rhs) {
    return new Tensor(this.#_native_self.lessThan(rhs.#_native_self))
  }

  bitwiseAnd(rhs) {
    return new Tensor(this.#_native_self.bitwiseAnd(rhs.#_native_self))
  }

  eq(rhs) {
    return new Tensor(this.#_native_self.eq(rhs.#_native_self))
  }

  bitwiseXor(rhs) {
    return new Tensor(this.#_native_self.bitwiseXor(rhs.#_native_self))
  }

  add(rhs) {
    return new Tensor(this.#_native_self.add(rhs.#_native_self))
  }

  sub(rhs) {
    return new Tensor(this.#_native_self.sub(rhs.#_native_self))
  }

  logicalAnd(rhs) {
    return new Tensor(this.#_native_self.logicalAnd(rhs.#_native_self))
  }

  lShift(rhs) {
    return new Tensor(this.#_native_self.lShift(rhs.#_native_self))
  }

  logicalOr(rhs) {
    return new Tensor(this.#_native_self.logicalOr(rhs.#_native_self))
  }

  neq(rhs) {
    return new Tensor(this.#_native_self.neq(rhs.#_native_self))
  }

  rShift(rhs) {
    return new Tensor(this.#_native_self.rShift(rhs.#_native_self))
  }

  div(rhs) {
    return new Tensor(this.#_native_self.div(rhs.#_native_self))
  }

  greaterThan(rhs) {
    return new Tensor(this.#_native_self.greaterThan(rhs.#_native_self))
  }

  greaterThanEqual(rhs) {
    return new Tensor(this.#_native_self.greaterThanEqual(rhs.#_native_self))
  }

  bitwiseOr(rhs) {
    return new Tensor(this.#_native_self.bitwiseOr(rhs.#_native_self))
  }

  mul(rhs) {
    return new Tensor(this.#_native_self.mul(rhs.#_native_self))
  }

  lessThanEqual(rhs) {
    return new Tensor(this.#_native_self.lessThanEqual(rhs.#_native_self))
  }

  copy() {
    return new Tensor(this.#_native_self.copy())
  }

  shape() {
    return this.#_native_self.shape()
  }

  elements() {
    return this.#_native_self.elements()
  }

  ndim() {
    return this.#_native_self.ndim()
  }

  isEmpty() {
    return this.#_native_self.isEmpty()
  }

  bytes() {
    return this.#_native_self.bytes()
  }

  type() {
    return this.#_native_self.type()
  }

  isSparse() {
    return this.#_native_self.isSparse()
  }

  strides() {
    return this.#_native_self.strides()
  }

  astype() {
    return new Tensor(this.#_native_self.astype())
  }

  flatten() {
    return new Tensor(this.#_native_self.flatten())
  }

  asContiguousTensor() {
    return new Tensor(this.#_native_self.asContiguousTensor())
  }

  isContiguous() {
    return this.#_native_self.isContiguous()
  }

  toFloat32Array() {
    return this.#_native_self.toFloat32Array()
  }

  toFloat64Array() {
    return this.#_native_self.toFloat64Array()
  }

  toBoolInt8Array() {
    return this.#_native_self.toBoolInt8Array()
  }

  toInt16Array() {
    return this.#_native_self.toInt16Array()
  }

  toInt32Array() {
    return this.#_native_self.toInt32Array()
  }

  save(filename) {
    return this.#_native_self.save(filename)
  }

  toInt64Array() {
    return this.#_native_self.toInt64Array()
  }

  toUint8Array() {
    return this.#_native_self.toUint8Array()
  }

  toUint16Array() {
    return this.#_native_self.toUint16Array()
  }

  toUint32Array() {
    return this.#_native_self.toUint32Array()
  }

  toUint64Array() {
    return this.#_native_self.toUint64Array()
  }

  toFloat32Scalar() {
    return this.#_native_self.toFloat32Scalar()
  }

  toFloat64Scalar() {
    return this.#_native_self.toFloat64Scalar()
  }

  toBoolInt8Scalar() {
    return this.#_native_self.toBoolInt8Scalar()
  }

  toInt16Scalar() {
    return this.#_native_self.toInt16Scalar()
  }

  toInt32Scalar() {
    return this.#_native_self.toInt32Scalar()
  }

  toInt64Scalar() {
    return this.#_native_self.toInt64Scalar()
  }

  toUint8Scalar() {
    return this.#_native_self.toUint8Scalar()
  }

  toUint16Scalar() {
    return this.#_native_self.toUint16Scalar()
  }

  toUint32Scalar() {
    return this.#_native_self.toUint32Scalar()
  }

  toUint64Scalar() {
    return this.#_native_self.toUint64Scalar()
  }

  eval() {
    return this.#_native_self.eval()
  }

  dispose() {
    return this.#_native_self.dispose()
  }
}

const amin = (input, axes, keepDims) => {
  return new Tensor(_amin(input._native_self, axes, keepDims))
}

const iota = (dims, tileDims) => {
  return new Tensor(_iota(dims, tileDims))
}

const log = (tensor) => {
  return new Tensor(_log(tensor._native_self))
}

const log1p = (tensor) => {
  return new Tensor(_log1p(tensor._native_self))
}

const sign = (tensor) => {
  return new Tensor(_sign(tensor._native_self))
}

const tril = (tensor) => {
  return new Tensor(_tril(tensor._native_self))
}

const maximum = (lhs, rhs) => {
  return new Tensor(_maximum(lhs._native_self, rhs._native_self))
}

const all = (input, axes, keepDims) => {
  return new Tensor(_all(input._native_self, axes, keepDims))
}

const arange = (start, end, step) => {
  return new Tensor(_arange(start, end, step))
}

const reshape = (tensor, shape) => {
  return new Tensor(_reshape(tensor._native_self, shape))
}

const negative = (tensor) => {
  return new Tensor(_negative(tensor._native_self))
}

const tanh = (tensor) => {
  return new Tensor(_tanh(tensor._native_self))
}

const floor = (tensor) => {
  return new Tensor(_floor(tensor._native_self))
}

const std = (input, axes, keepDims) => {
  return new Tensor(_std(input._native_self, axes, keepDims))
}

const sin = (tensor) => {
  return new Tensor(_sin(tensor._native_self))
}

const ceil = (tensor) => {
  return new Tensor(_ceil(tensor._native_self))
}

const erf = (tensor) => {
  return new Tensor(_erf(tensor._native_self))
}

const clip = (tensor, low, high) => {
  return new Tensor(_clip(tensor._native_self, low._native_self, high._native_self))
}

const matmul = (lhs, rhs) => {
  return new Tensor(_matmul(lhs._native_self, rhs._native_self))
}

const where = (condition, x, y) => {
  return new Tensor(_where(condition._native_self, x._native_self, y._native_self))
}

const sort = (input, axis) => {
  return new Tensor(_sort(input._native_self, axis))
}

const full = (dims, val) => {
  return new Tensor(_full(dims, val))
}

const identity = (dim) => {
  return new Tensor(_identity(dim))
}

const transpose = (tensor, axes) => {
  return new Tensor(_transpose(tensor._native_self, axes))
}

const sigmoid = (tensor) => {
  return new Tensor(_sigmoid(tensor._native_self))
}

const roll = (tensor, shift, axis) => {
  return new Tensor(_roll(tensor._native_self, shift, axis))
}

const isnan = (tensor) => {
  return new Tensor(_isnan(tensor._native_self))
}

const sum = (input, axes, keepDims) => {
  return new Tensor(_sum(input._native_self, axes, keepDims))
}

const median = (input, axes, keepDims) => {
  return new Tensor(_median(input._native_self, axes, keepDims))
}

const nonzero = (tensor) => {
  return new Tensor(_nonzero(tensor._native_self))
}

const sqrt = (tensor) => {
  return new Tensor(_sqrt(tensor._native_self))
}

const argmin = (input, axis, keepDims) => {
  return new Tensor(_argmin(input._native_self, axis, keepDims))
}

const mean = (input, axes, keepDims) => {
  return new Tensor(_mean(input._native_self, axes, keepDims))
}

const _var = (input, axes, bias, keepDims) => {
  return new Tensor(__var(input._native_self, axes, bias, keepDims))
}

const countNonzero = (input, axes, keepDims) => {
  return new Tensor(_countNonzero(input._native_self, axes, keepDims))
}

const concatenate = (tensors, axis) => {
  return new Tensor(_concatenate(tensors, axis))
}

const exp = (tensor) => {
  return new Tensor(_exp(tensor._native_self))
}

const rint = (tensor) => {
  return new Tensor(_rint(tensor._native_self))
}

const flip = (tensor, dim) => {
  return new Tensor(_flip(tensor._native_self, dim))
}

const power = (lhs, rhs) => {
  return new Tensor(_power(lhs._native_self, rhs._native_self))
}

const norm = (input, axes, p, keepDims) => {
  return new Tensor(_norm(input._native_self, axes, p, keepDims))
}

const cos = (tensor) => {
  return new Tensor(_cos(tensor._native_self))
}

const minimum = (lhs, rhs) => {
  return new Tensor(_minimum(lhs._native_self, rhs._native_self))
}

const amax = (input, axes, keepDims) => {
  return new Tensor(_amax(input._native_self, axes, keepDims))
}

const cumsum = (input, axis) => {
  return new Tensor(_cumsum(input._native_self, axis))
}

const any = (input, axes, keepDims) => {
  return new Tensor(_any(input._native_self, axes, keepDims))
}

const tile = (tensor, shape) => {
  return new Tensor(_tile(tensor._native_self, shape))
}

const logicalNot = (tensor) => {
  return new Tensor(_logicalNot(tensor._native_self))
}

const absolute = (tensor) => {
  return new Tensor(_absolute(tensor._native_self))
}

const isinf = (tensor) => {
  return new Tensor(_isinf(tensor._native_self))
}

const triu = (tensor) => {
  return new Tensor(_triu(tensor._native_self))
}

const argmax = (input, axis, keepDims) => {
  return new Tensor(_argmax(input._native_self, axis, keepDims))
}

const lessThanEqual = (lhs, rhs) => {
  return new Tensor(_lessThanEqual(lhs._native_self, rhs._native_self))
}

const greaterThanEqual = (lhs, rhs) => {
  return new Tensor(_greaterThanEqual(lhs._native_self, rhs._native_self))
}

const bitwiseOr = (lhs, rhs) => {
  return new Tensor(_bitwiseOr(lhs._native_self, rhs._native_self))
}

const mul = (lhs, rhs) => {
  return new Tensor(_mul(lhs._native_self, rhs._native_self))
}

const bitwiseAnd = (lhs, rhs) => {
  return new Tensor(_bitwiseAnd(lhs._native_self, rhs._native_self))
}

const mod = (lhs, rhs) => {
  return new Tensor(_mod(lhs._native_self, rhs._native_self))
}

const lessThan = (lhs, rhs) => {
  return new Tensor(_lessThan(lhs._native_self, rhs._native_self))
}

const lShift = (lhs, rhs) => {
  return new Tensor(_lShift(lhs._native_self, rhs._native_self))
}

const eq = (lhs, rhs) => {
  return new Tensor(_eq(lhs._native_self, rhs._native_self))
}

const bitwiseXor = (lhs, rhs) => {
  return new Tensor(_bitwiseXor(lhs._native_self, rhs._native_self))
}

const add = (lhs, rhs) => {
  return new Tensor(_add(lhs._native_self, rhs._native_self))
}

const sub = (lhs, rhs) => {
  return new Tensor(_sub(lhs._native_self, rhs._native_self))
}

const logicalAnd = (lhs, rhs) => {
  return new Tensor(_logicalAnd(lhs._native_self, rhs._native_self))
}

const greaterThan = (lhs, rhs) => {
  return new Tensor(_greaterThan(lhs._native_self, rhs._native_self))
}

const logicalOr = (lhs, rhs) => {
  return new Tensor(_logicalOr(lhs._native_self, rhs._native_self))
}

const neq = (lhs, rhs) => {
  return new Tensor(_neq(lhs._native_self, rhs._native_self))
}

const rShift = (lhs, rhs) => {
  return new Tensor(_rShift(lhs._native_self, rhs._native_self))
}

const div = (lhs, rhs) => {
  return new Tensor(_div(lhs._native_self, rhs._native_self))
}

const init = () => {
  return _init()
}

const bytesUsed = () => {
  return _bytesUsed()
}

const setRowMajor = () => {
  return _setRowMajor()
}

const setColMajor = () => {
  return _setColMajor()
}

const isRowMajor = () => {
  return _isRowMajor()
}

const isColMajor = () => {
  return _isColMajor()
}

const dtypeFloat32 = () => {
  return _dtypeFloat32()
}

const dtypeFloat64 = () => {
  return _dtypeFloat64()
}

const dtypeBoolInt8 = () => {
  return _dtypeBoolInt8()
}

const dtypeInt16 = () => {
  return _dtypeInt16()
}

const dtypeInt32 = () => {
  return _dtypeInt32()
}

const dtypeInt64 = () => {
  return _dtypeInt64()
}

const dtypeUint8 = () => {
  return _dtypeUint8()
}

const dtypeUint16 = () => {
  return _dtypeUint16()
}

const dtypeUint32 = () => {
  return _dtypeUint32()
}

const dtypeUint64 = () => {
  return _dtypeUint64()
}

const rand = (shape) => {
  return new Tensor(_rand(shape))
}

const randn = (shape) => {
  return new Tensor(_randn(shape))
}

module.exports = {
  Tensor,
  exp,
  rint,
  flip,
  power,
  norm,
  countNonzero,
  concatenate,
  minimum,
  amax,
  cumsum,
  any,
  cos,
  logicalNot,
  absolute,
  isinf,
  triu,
  argmax,
  tile,
  log,
  log1p,
  sign,
  tril,
  maximum,
  amin,
  iota,
  reshape,
  negative,
  tanh,
  floor,
  std,
  all,
  arange,
  ceil,
  erf,
  clip,
  matmul,
  sin,
  identity,
  transpose,
  sigmoid,
  roll,
  isnan,
  where,
  sort,
  full,
  median,
  sum,
  sqrt,
  argmin,
  mean,
  _var,
  nonzero,
  neq,
  rShift,
  div,
  greaterThan,
  logicalOr,
  bitwiseOr,
  mul,
  lessThanEqual,
  greaterThanEqual,
  lessThan,
  bitwiseAnd,
  mod,
  bitwiseXor,
  add,
  sub,
  logicalAnd,
  lShift,
  eq,
  init,
  bytesUsed,
  setRowMajor,
  setColMajor,
  isRowMajor,
  isColMajor,
  dtypeFloat32,
  dtypeFloat64,
  dtypeBoolInt8,
  dtypeInt16,
  dtypeInt32,
  dtypeInt64,
  dtypeUint8,
  dtypeUint16,
  dtypeUint32,
  dtypeUint64,
  rand,
  randn
}
