// Code generated by gen-napi. DO NOT EDIT.
const {
,
  _foo,
  _bar
} = require("../../build/Release/test.node")

export const foo = (a: number): number => {
  return _foo(a);
}

export const bar = (a: number, b: number): number => {
  return _bar(a, b);
}

