// Code generated by gen-napi. DO NOT EDIT.

//////////
// source: TensorBase.h

var TensorBackendType;
(function (TensorBackendType) {
  TensorBackendType[(TensorBackendType['Stub'] = 0)] = 'Stub';
  TensorBackendType[(TensorBackendType['Tracer'] = 1)] = 'Tracer';
  TensorBackendType[(TensorBackendType['ArrayFire'] = 2)] = 'ArrayFire';
  TensorBackendType[(TensorBackendType['OneDnn'] = 3)] = 'OneDnn';
  TensorBackendType[(TensorBackendType['Jit'] = 4)] = 'Jit';
})(TensorBackendType || (TensorBackendType = {}));
exports.TensorBackendType = TensorBackendType;

var Location;
(function (Location) {
  Location[(Location['Host'] = 0)] = 'Host';
  Location[(Location['Device'] = 1)] = 'Device';
})(Location || (Location = {}));
exports.Location = Location;

var StorageType;
(function (StorageType) {
  StorageType[(StorageType['Dense'] = 0)] = 'Dense';
  StorageType[(StorageType['CSR'] = 1)] = 'CSR';
  StorageType[(StorageType['CSC'] = 2)] = 'CSC';
  StorageType[(StorageType['COO'] = 3)] = 'COO';
})(StorageType || (StorageType = {}));
exports.StorageType = StorageType;

var PadType;
(function (PadType) {
  PadType[(PadType['Constant'] = 0)] = 'Constant';
  PadType[(PadType['Edge'] = 1)] = 'Edge';
  PadType[(PadType['Symmetric'] = 2)] = 'Symmetric';
})(PadType || (PadType = {}));
exports.PadType = PadType;

var SortMode;
(function (SortMode) {
  SortMode[(SortMode['Descending'] = 0)] = 'Descending';
  SortMode[(SortMode['Ascending'] = 1)] = 'Ascending';
})(SortMode || (SortMode = {}));
exports.SortMode = SortMode;

var MatrixProperty;
(function (MatrixProperty) {
  MatrixProperty[(MatrixProperty['None'] = 0)] = 'None';
  MatrixProperty[(MatrixProperty['Transpose'] = 1)] = 'Transpose';
})(MatrixProperty || (MatrixProperty = {}));
exports.MatrixProperty = MatrixProperty;

var dtype;
(function (dtype) {
  dtype[(dtype['f16'] = 0)] = 'f16';
  dtype[(dtype['f32'] = 1)] = 'f32';
  dtype[(dtype['f64'] = 2)] = 'f64';
  dtype[(dtype['b8'] = 3)] = 'b8';
  dtype[(dtype['s16'] = 4)] = 's16';
  dtype[(dtype['s32'] = 5)] = 's32';
  dtype[(dtype['s64'] = 6)] = 's64';
  dtype[(dtype['u8'] = 7)] = 'u8';
  dtype[(dtype['u16'] = 8)] = 'u16';
  dtype[(dtype['u32'] = 9)] = 'u32';
  dtype[(dtype['u64'] = 10)] = 'u64';
})(dtype || (dtype = {}));
exports.dtype = dtype;
