name: goreleaser

on:
  pull_request:
  push:

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      - name: Capture OSXSDK path
        run: |
          echo "SYSROOT=$(xcrun --show-sdk-path)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: master
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '>=1.19'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
